import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex">
          <div className="w-full max-w-xs bg-white rounded-xl shadow-md p-6 space-y-6">
            {/* Title */}
            <div>
              <h1 className="text-2xl font-bold text-gray-800 mb-1">
                Dashboard Layout
              </h1>
              <p className="text-sm text-gray-500">
                Manage your account settings and preferences.
              </p>
            </div>

            {/* Navigation Links */}
            <ul className="space-y-2">
              <li>
                <Link
                  href="/dashboared/profile"
                  className="block w-full rounded-lg px-4 py-2 text-gray-700 hover:bg-blue-100 hover:text-blue-700 transition"
                >
                  Profile
                </Link>
              </li>
              <li>
                <Link
                  href="/dashboared/settings"
                  className="block w-full rounded-lg px-4 py-2 text-gray-700 hover:bg-blue-100 hover:text-blue-700 transition"
                >
                  Settings
                </Link>
              </li>
              <li>
                <Link
                  href="/dashboared/invoices"
                  className="block w-full rounded-lg px-4 py-2 text-gray-700 hover:bg-blue-100 hover:text-blue-700 transition"
                >
                  Invoices
                </Link>
              </li>
              <li>
                <Link
                  href="/dashboared/transactions"
                  className="block w-full rounded-lg px-4 py-2 text-gray-700 hover:bg-blue-100 hover:text-blue-700 transition"
                >
                  Transactions
                </Link>
              </li>
            </ul>
          </div>

          <div className="flex justify-center w-screen items-center h-screen  p-4">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
